name: perx
description: A permissions group plugin
main: io.github.aparx.perx.Main
version: '${project.version}'
author: "aparx (@bonedfps)"
api-version: 1.16
website: "https://github.com/aparx/perx"

commands:
  perx:
    usage: "<...>"
    description: "The root perx command (use /perx help)"